[package]
name = "s2-sys-bind"
version = "0.1.0"
edition = "2021"
description = "Generate S2 C API bindings"

[dependencies]
bindgen = "0.70.0"
clap = { version = "3.2.6", features = ["derive"] }
pkg-config = "0.3.25"
regex = "1.5"
semver = "1.0"
