[package]
name = "s2-sys"
version = "0.1.0"
license = "MIT"
edition = "2021"
build = "build.rs"

[dependencies]
libc = "~0.2"
link-cplusplus = { version = "1.0", optional = true }

[lib]
name = "s2_sys"

[features]
# static = ["geos-src", "link-cplusplus"]
